/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import './config';

export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { AttendanceByAuthorityDto } from './models/AttendanceByAuthorityDto';
export type { ChangePasswordDto } from './models/ChangePasswordDto';
export type { ChangePasswordInternalErrorDto } from './models/ChangePasswordInternalErrorDto';
export type { ChangePasswordSuccessDto } from './models/ChangePasswordSuccessDto';
export type { ChangePasswordThrottlerDto } from './models/ChangePasswordThrottlerDto';
export type { ChangePasswordUnauthorizedDto } from './models/ChangePasswordUnauthorizedDto';
export type { ChangePasswordValidationDto } from './models/ChangePasswordValidationDto';
export type { CreateDepartmentDto } from './models/CreateDepartmentDto';
export type { CreateDesignationDto } from './models/CreateDesignationDto';
export type { CreateRoleDto } from './models/CreateRoleDto';
export { CreateSellsShiftManagementDto } from './models/CreateSellsShiftManagementDto';
export type { CreateUserDto } from './models/CreateUserDto';
export type { DepartmentByIdSuccessDto } from './models/DepartmentByIdSuccessDto';
export type { DepartmentCreateConflictDto } from './models/DepartmentCreateConflictDto';
export type { DepartmentCreateInternalErrorDto } from './models/DepartmentCreateInternalErrorDto';
export type { DepartmentCreateSuccessDto } from './models/DepartmentCreateSuccessDto';
export type { DepartmentCreateUnauthorizedDto } from './models/DepartmentCreateUnauthorizedDto';
export type { DepartmentCreateValidationDto } from './models/DepartmentCreateValidationDto';
export type { DepartmentDeleteByIdNotFoundDto } from './models/DepartmentDeleteByIdNotFoundDto';
export type { DepartmentDeleteForbiddenDto } from './models/DepartmentDeleteForbiddenDto';
export type { DepartmentDeleteInternalErrorDto } from './models/DepartmentDeleteInternalErrorDto';
export type { DepartmentDeleteSuccessDto } from './models/DepartmentDeleteSuccessDto';
export type { DepartmentDeleteUnauthorizedDto } from './models/DepartmentDeleteUnauthorizedDto';
export type { DepartmentDeleteValidationDto } from './models/DepartmentDeleteValidationDto';
export type { DepartmentGetByIdValidationDto } from './models/DepartmentGetByIdValidationDto';
export type { DepartmentInternalErrorDto } from './models/DepartmentInternalErrorDto';
export type { DepartmentNotFoundDto } from './models/DepartmentNotFoundDto';
export type { DepartmentPatchSuccessDto } from './models/DepartmentPatchSuccessDto';
export type { DepartmentsListSuccessDto } from './models/DepartmentsListSuccessDto';
export type { DepartmentsValidationDto } from './models/DepartmentsValidationDto';
export type { DepartmentUpdateByIdNotFoundDto } from './models/DepartmentUpdateByIdNotFoundDto';
export type { DepartmentUpdateConflictDto } from './models/DepartmentUpdateConflictDto';
export type { DepartmentUpdateForbiddenDto } from './models/DepartmentUpdateForbiddenDto';
export type { DepartmentUpdateInternalErrorDto } from './models/DepartmentUpdateInternalErrorDto';
export type { DepartmentUpdateUnauthorizedDto } from './models/DepartmentUpdateUnauthorizedDto';
export type { DepartmentUpdateValidationDto } from './models/DepartmentUpdateValidationDto';
export type { DesignationCreateConflictDto } from './models/DesignationCreateConflictDto';
export type { DesignationCreateForbiddenDto } from './models/DesignationCreateForbiddenDto';
export type { DesignationCreateInternalErrorDto } from './models/DesignationCreateInternalErrorDto';
export type { DesignationCreateUnauthorizedDto } from './models/DesignationCreateUnauthorizedDto';
export type { DesignationCreateValidationDto } from './models/DesignationCreateValidationDto';
export type { DesignationDeleteByIdNotFoundDto } from './models/DesignationDeleteByIdNotFoundDto';
export type { DesignationDeleteInternalErrorDto } from './models/DesignationDeleteInternalErrorDto';
export type { DesignationDeleteUnauthorizedDto } from './models/DesignationDeleteUnauthorizedDto';
export type { DesignationDeleteValidationDto } from './models/DesignationDeleteValidationDto';
export type { DesignationGetByIdValidationDto } from './models/DesignationGetByIdValidationDto';
export type { DesignationInternalErrorDto } from './models/DesignationInternalErrorDto';
export type { DesignationListSuccessDto } from './models/DesignationListSuccessDto';
export type { DesignationNotFoundDto } from './models/DesignationNotFoundDto';
export type { DesignationsInternalErrorDto } from './models/DesignationsInternalErrorDto';
export type { DesignationSuccessDto } from './models/DesignationSuccessDto';
export type { DesignationsValidationDto } from './models/DesignationsValidationDto';
export type { DesignationUpdateByIdNotFoundDto } from './models/DesignationUpdateByIdNotFoundDto';
export type { DesignationUpdateConflictDto } from './models/DesignationUpdateConflictDto';
export type { DesignationUpdateForbiddenDto } from './models/DesignationUpdateForbiddenDto';
export type { DesignationUpdateInternalErrorDto } from './models/DesignationUpdateInternalErrorDto';
export type { DesignationUpdateUnauthorizedDto } from './models/DesignationUpdateUnauthorizedDto';
export type { DesignationUpdateValidationDto } from './models/DesignationUpdateValidationDto';
export type { FieldErrorDto } from './models/FieldErrorDto';
export type { ForgotPasswordDto } from './models/ForgotPasswordDto';
export type { ForgotPasswordInternalErrorDto } from './models/ForgotPasswordInternalErrorDto';
export type { ForgotPasswordSuccessDto } from './models/ForgotPasswordSuccessDto';
export type { ForgotPasswordThrottlerDto } from './models/ForgotPasswordThrottlerDto';
export type { ForgotPasswordValidationDto } from './models/ForgotPasswordValidationDto';
export type { GetAttendanceDto } from './models/GetAttendanceDto';
export type { LoginDto } from './models/LoginDto';
export type { LoginInternalErrorDto } from './models/LoginInternalErrorDto';
export type { LoginSuccessDto } from './models/LoginSuccessDto';
export type { LoginUnauthorizedDto } from './models/LoginUnauthorizedDto';
export type { LoginValidationDto } from './models/LoginValidationDto';
export type { LogoutInternalErrorDto } from './models/LogoutInternalErrorDto';
export type { LogoutSuccessDto } from './models/LogoutSuccessDto';
export type { LogoutUnauthorizedDto } from './models/LogoutUnauthorizedDto';
export type { MarkAttendanceAsAuthorityForbiddenDto } from './models/MarkAttendanceAsAuthorityForbiddenDto';
export type { MarkAttendanceAsAuthorityInternalErrorDto } from './models/MarkAttendanceAsAuthorityInternalErrorDto';
export type { MarkAttendanceAsAuthorityNotFoundDtoDto } from './models/MarkAttendanceAsAuthorityNotFoundDtoDto';
export type { MarkAttendanceAsAuthoritySuccessDto } from './models/MarkAttendanceAsAuthoritySuccessDto';
export type { MarkAttendanceAsAuthorityUnauthorizedDto } from './models/MarkAttendanceAsAuthorityUnauthorizedDto';
export type { MarkAttendanceAsAuthorityValidationDto } from './models/MarkAttendanceAsAuthorityValidationDto';
export type { MarkAttendanceForbiddenDto } from './models/MarkAttendanceForbiddenDto';
export type { MarkAttendanceInternalErrorDto } from './models/MarkAttendanceInternalErrorDto';
export type { MarkAttendanceNotFoundDto } from './models/MarkAttendanceNotFoundDto';
export type { MarkAttendanceSuccessDto } from './models/MarkAttendanceSuccessDto';
export type { MarkAttendanceUnauthorizedDto } from './models/MarkAttendanceUnauthorizedDto';
export type { MarkOutAttendanceForbiddenDto } from './models/MarkOutAttendanceForbiddenDto';
export type { MarkOutAttendanceInternalErrorDto } from './models/MarkOutAttendanceInternalErrorDto';
export type { MarkOutAttendanceNotFoundDto } from './models/MarkOutAttendanceNotFoundDto';
export type { MarkOutAttendanceSuccessDto } from './models/MarkOutAttendanceSuccessDto';
export type { MarkOutAttendanceUnauthorizedDto } from './models/MarkOutAttendanceUnauthorizedDto';
export type { MarkWeekendExchangeAsAuthorityForbiddenDto } from './models/MarkWeekendExchangeAsAuthorityForbiddenDto';
export type { MarkWeekendExchangeAsAuthorityInternalErrorDto } from './models/MarkWeekendExchangeAsAuthorityInternalErrorDto';
export type { MarkWeekendExchangeAsAuthorityNotFoundDto } from './models/MarkWeekendExchangeAsAuthorityNotFoundDto';
export type { MarkWeekendExchangeAsAuthorityUnauthorizedDto } from './models/MarkWeekendExchangeAsAuthorityUnauthorizedDto';
export type { MarkWeekendExchangeAsAuthorityValidationDto } from './models/MarkWeekendExchangeAsAuthorityValidationDto';
export type { MarkWeekendExchangeByAuthoritySuccessDto } from './models/MarkWeekendExchangeByAuthoritySuccessDto';
export type { MongoIdDto } from './models/MongoIdDto';
export type { MyAttendanceForbiddenDto } from './models/MyAttendanceForbiddenDto';
export type { MyAttendanceInternalErrorDto } from './models/MyAttendanceInternalErrorDto';
export type { MyAttendanceSuccessDto } from './models/MyAttendanceSuccessDto';
export type { MyAttendanceUnauthorizedDto } from './models/MyAttendanceUnauthorizedDto';
export type { MyAttendanceValidationDto } from './models/MyAttendanceValidationDto';
export type { Object } from './models/Object';
export type { RegistrationEmailConflictDto } from './models/RegistrationEmailConflictDto';
export type { RegistrationInternalErrorDto } from './models/RegistrationInternalErrorDto';
export type { RegistrationRoleNotFoundDto } from './models/RegistrationRoleNotFoundDto';
export type { RegistrationSuccessDto } from './models/RegistrationSuccessDto';
export type { RegistrationValidationDto } from './models/RegistrationValidationDto';
export type { ResetPasswordDto } from './models/ResetPasswordDto';
export type { ResetPasswordInternalErrorDto } from './models/ResetPasswordInternalErrorDto';
export type { ResetPasswordSuccessDto } from './models/ResetPasswordSuccessDto';
export type { ResetPasswordThrottlerDto } from './models/ResetPasswordThrottlerDto';
export type { ResetPasswordValidationDto } from './models/ResetPasswordValidationDto';
export type { RoleByIdSuccessDto } from './models/RoleByIdSuccessDto';
export type { RoleCreateConflictDto } from './models/RoleCreateConflictDto';
export type { RoleCreateForbiddenDto } from './models/RoleCreateForbiddenDto';
export type { RoleCreateInternalErrorDto } from './models/RoleCreateInternalErrorDto';
export type { RoleCreateSuccessDto } from './models/RoleCreateSuccessDto';
export type { RoleCreateUnauthorizedDto } from './models/RoleCreateUnauthorizedDto';
export type { RoleCreateValidationDto } from './models/RoleCreateValidationDto';
export type { RoleDeleteByIdNotFoundDto } from './models/RoleDeleteByIdNotFoundDto';
export type { RoleDeleteForbiddenDto } from './models/RoleDeleteForbiddenDto';
export type { RoleDeleteInternalErrorDto } from './models/RoleDeleteInternalErrorDto';
export type { RoleDeleteSuccessDto } from './models/RoleDeleteSuccessDto';
export type { RoleDeleteUnauthorizedDto } from './models/RoleDeleteUnauthorizedDto';
export type { RoleDeleteValidationDto } from './models/RoleDeleteValidationDto';
export type { RoleGetByIdValidationDto } from './models/RoleGetByIdValidationDto';
export type { RoleInternalErrorDto } from './models/RoleInternalErrorDto';
export type { RoleNotFoundDto } from './models/RoleNotFoundDto';
export type { RolePatchSuccessDto } from './models/RolePatchSuccessDto';
export type { RolesInternalErrorDto } from './models/RolesInternalErrorDto';
export type { RolesListSuccessDto } from './models/RolesListSuccessDto';
export type { RolesValidationDto } from './models/RolesValidationDto';
export type { RoleUpdateByIdNotFoundDto } from './models/RoleUpdateByIdNotFoundDto';
export type { RoleUpdateConflictDto } from './models/RoleUpdateConflictDto';
export type { RoleUpdateForbiddenDto } from './models/RoleUpdateForbiddenDto';
export type { RoleUpdateInternalErrorDto } from './models/RoleUpdateInternalErrorDto';
export type { RoleUpdateUnauthorizedDto } from './models/RoleUpdateUnauthorizedDto';
export type { RoleUpdateValidationDto } from './models/RoleUpdateValidationDto';
export type { SearchQueryDto } from './models/SearchQueryDto';
export type { SingleUserAttendanceForbiddenDto } from './models/SingleUserAttendanceForbiddenDto';
export type { SingleUserAttendanceInternalErrorDto } from './models/SingleUserAttendanceInternalErrorDto';
export type { SingleUserAttendanceNotFoundDto } from './models/SingleUserAttendanceNotFoundDto';
export type { SingleUserAttendanceSuccessDto } from './models/SingleUserAttendanceSuccessDto';
export type { SingleUserAttendanceUnauthorizedDto } from './models/SingleUserAttendanceUnauthorizedDto';
export type { SingleUserAttendanceValidationDto } from './models/SingleUserAttendanceValidationDto';
export type { UpdateByAuthorityWeekendSetDto } from './models/UpdateByAuthorityWeekendSetDto';
export type { UpdateByAuthorityWeekendSetForbiddenDto } from './models/UpdateByAuthorityWeekendSetForbiddenDto';
export type { UpdateByAuthorityWeekendSetInternalErrorDto } from './models/UpdateByAuthorityWeekendSetInternalErrorDto';
export type { UpdateByAuthorityWeekendSetNotFoundDto } from './models/UpdateByAuthorityWeekendSetNotFoundDto';
export type { UpdateByAuthorityWeekendSetSuccessDto } from './models/UpdateByAuthorityWeekendSetSuccessDto';
export type { UpdateByAuthorityWeekendSetUnauthorizedDto } from './models/UpdateByAuthorityWeekendSetUnauthorizedDto';
export type { UpdateByAuthorityWeekendSetValidationDto } from './models/UpdateByAuthorityWeekendSetValidationDto';
export type { UpdateDepartmentDto } from './models/UpdateDepartmentDto';
export type { UpdateDesignationDto } from './models/UpdateDesignationDto';
export type { UpdateRoleDto } from './models/UpdateRoleDto';
export type { UpdateUserProfileDto } from './models/UpdateUserProfileDto';
export type { UpdateUserProfileInternalErrorDto } from './models/UpdateUserProfileInternalErrorDto';
export type { UpdateUserProfileUnauthorizedDto } from './models/UpdateUserProfileUnauthorizedDto';
export type { UserForbiddenDto } from './models/UserForbiddenDto';
export type { UserIdDto } from './models/UserIdDto';
export type { UserInternalErrorDto } from './models/UserInternalErrorDto';
export type { UserNotFoundDto } from './models/UserNotFoundDto';
export type { UserProfileInternalErrorDto } from './models/UserProfileInternalErrorDto';
export type { UserProfileSuccessDto } from './models/UserProfileSuccessDto';
export type { UserProfileUnauthorizedDto } from './models/UserProfileUnauthorizedDto';
export type { UserProfileUpdateSuccessDto } from './models/UserProfileUpdateSuccessDto';
export type { UserProfileUpdateValidationDto } from './models/UserProfileUpdateValidationDto';
export type { UsersForbiddenDto } from './models/UsersForbiddenDto';
export type { UsersInternalErrorDto } from './models/UsersInternalErrorDto';
export type { UsersListSuccessDto } from './models/UsersListSuccessDto';
export type { UserSuccessDto } from './models/UserSuccessDto';
export type { UsersUnauthorizedDto } from './models/UsersUnauthorizedDto';
export type { UsersValidationDto } from './models/UsersValidationDto';
export type { UserUnauthorizedDto } from './models/UserUnauthorizedDto';
export type { UserValidationDto } from './models/UserValidationDto';
export type { WeekendExchangeByAuthorityDto } from './models/WeekendExchangeByAuthorityDto';

export { AppService } from './services/AppService';
export { AttendanceService } from './services/AttendanceService';
export { AuthenticationService } from './services/AuthenticationService';
export { DepartmentService } from './services/DepartmentService';
export { DesignationService } from './services/DesignationService';
export { RoleService } from './services/RoleService';
export { SellsShiftManagementService } from './services/SellsShiftManagementService';
export { UserService } from './services/UserService';
